Reverted some commits
Reverted back to main re-write commit
Fixed syntax issue on line 53
Cleaned up step 3 'Download OFP firmware'

diff --git a/.github/workflows/ofp-decrypt.yml b/.github/workflows/ofp-decrypt.yml
--- a/.github/workflows/ofp-decrypt.yml
+++ b/.github/workflows/ofp-decrypt.yml
@@ -41,7 +41,7 @@ jobs:
       - name: Checkout
         uses: actions/checkout@main
 
-      - name: Clean up working environment
+      - name: CleanUp Enviroment
         if: ${{ github.event.inputs.bigfile == 'YES' }}
         uses: rokibhasansagar/slimhub_actions@main
 
@@ -49,12 +49,16 @@ jobs:
         shell: bash
         run: |
           sudo apt-fast update -qqy
-          sudo apt-fast install -qqy coreutils p7zip-full p7zip-rar
-          aria2c -c -s16 -x16 "$OFP_LINK" 2>/dev/null
+          sudo apt-fast install -qqy coreutils p7zip-full p7zip-rar python3 python3-pip rclone simg2img
+          aria2c -c -s16 -x16 "$OFP_LINK" 2>/dev/null || {
+            echo "Error: The provided URL is invalid." && exit 1
+          }
           file_extension=${OFP_LINK##*.}
           if [ "$file_extension" != "ofp" ]; then
             7z e *."${file_extension}" -y && rm *."${file_extension}"
-            mv $(find . -name "*.ofp") .
+            if [ ! -f *.ofp ]; then
+              mv $(find . -name "*.ofp") .
+            fi
           fi
           find . -type f ! -name "*.ofp" -delete
           OFPFILE=$(basename *.ofp)
@@ -65,7 +69,6 @@ jobs:
       - name: Prepare Decrypter and Decrypt OFP
         shell: bash
         run: |
-          sudo apt-fast install -qqy python3 python3-pip rclone simg2img
           curl -s "https://raw.githubusercontent.com/bkerler/oppo_decrypt/master/requirements.txt" -o "requirements.txt"
           pip3 install -r requirements.txt && rm requirements.txt
           mkdir "out"
